#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

$app = new Silex\Application();

$app['environment'] = 'dev';
require __DIR__.'/src/app.php';

$console = require __DIR__.'/src/console.php';
$console->run();